services:
    EzSystems\EzPlatformGraphQL\GraphQL\InputMapper\Search\Criterion\ContentTypeIdentifier:
        tags:
            - {name: 'ezplatform_graphql.query_input_visitor', inputKey: 'ContentTypeIdentifier'}

    EzSystems\EzPlatformGraphQL\GraphQL\InputMapper\Search\Criterion\ContentTypeId:
        tags:
            - {name: 'ezplatform_graphql.query_input_visitor', inputKey: 'ContentTypeId'}

    EzSystems\EzPlatformGraphQL\GraphQL\InputMapper\Search\Criterion\Text:
        tags:
            - {name: 'ezplatform_graphql.query_input_visitor', inputKey: 'Text'}

    EzSystems\EzPlatformGraphQL\GraphQL\InputMapper\Search\Criterion\Created:
        tags:
            - {name: 'ezplatform_graphql.query_input_visitor', inputKey: 'Created'}

    EzSystems\EzPlatformGraphQL\GraphQL\InputMapper\Search\Criterion\Modified:
        tags:
            - {name: 'ezplatform_graphql.query_input_visitor', inputKey: 'Modified'}

    EzSystems\EzPlatformGraphQL\GraphQL\InputMapper\Search\Criterion\Field:
        tags:
            - {name: 'ezplatform_graphql.query_input_visitor', inputKey: 'Field'}

    EzSystems\EzPlatformGraphQL\GraphQL\InputMapper\Search\Criterion\ParentLocationId:
      tags:
        - {name: 'ezplatform_graphql.query_input_visitor', inputKey: 'ParentLocationId'}

    EzSystems\EzPlatformGraphQL\GraphQL\InputMapper\Search\SortBy:
        tags:
            - {name: 'ezplatform_graphql.query_input_visitor', inputKey: 'SortBy'}
