services:
    EzSystems\EzPlatformGraphQL\GraphQL\InputMapper\Search\Criterion\ContentTypeId:
        class: EzSystems\EzPlatformGraphQL\GraphQL\InputMapper\Search\Criterion\Standard
        arguments:
            $criterionClass: 'eZ\Publish\API\Repository\Values\Content\Query\Criterion\ContentTypeId'
        tags:
            - {name: 'ezplatform_graphql.query_input_visitor', inputKey: 'ContentTypeId'}

    EzSystems\EzPlatformGraphQL\GraphQL\InputMapper\Search\Criterion\Text:
        class: EzSystems\EzPlatformGraphQL\GraphQL\InputMapper\Search\Criterion\Standard
        arguments:
            $criterionClass: 'eZ\Publish\API\Repository\Values\Content\Query\Criterion\Fulltext'
        tags:
            - {name: 'ezplatform_graphql.query_input_visitor', inputKey: 'Text'}

    EzSystems\EzPlatformGraphQL\GraphQL\InputMapper\Search\Criterion\ParentLocationId:
        class: EzSystems\EzPlatformGraphQL\GraphQL\InputMapper\Search\Criterion\Standard
        arguments:
            $criterionClass: 'eZ\Publish\API\Repository\Values\Content\Query\Criterion\ParentLocationId'
        tags:
            - {name: 'ezplatform_graphql.query_input_visitor', inputKey: 'ParentLocationId'}


    EzSystems\EzPlatformGraphQL\GraphQL\InputMapper\Search\Criterion\Created:
        tags:
            - {name: 'ezplatform_graphql.query_input_visitor', inputKey: 'Created'}

    EzSystems\EzPlatformGraphQL\GraphQL\InputMapper\Search\Criterion\Modified:
        tags:
            - {name: 'ezplatform_graphql.query_input_visitor', inputKey: 'Modified'}

    EzSystems\EzPlatformGraphQL\GraphQL\InputMapper\Search\Criterion\Field:
        tags:
            - {name: 'ezplatform_graphql.query_input_visitor', inputKey: 'Field'}

    EzSystems\EzPlatformGraphQL\GraphQL\InputMapper\Search\SortBy:
        tags:
            - {name: 'ezplatform_graphql.query_input_visitor', inputKey: 'SortBy'}
