services:
    EzSystems\EzPlatformGraphQL\GraphQL\InputMapper\Search\Criteria\ContentTypeId:
        class: EzSystems\EzPlatformGraphQL\GraphQL\InputMapper\Search\Criteria\CriterionClass
        arguments:
            $criterionClass: 'eZ\Publish\API\Repository\Values\Content\Query\Criterion\ContentTypeId'
        tags:
            - {name: 'ezplatform_graphql.query_input_visitor', inputKey: 'ContentTypeId'}

    EzSystems\EzPlatformGraphQL\GraphQL\InputMapper\Search\Criteria\Text:
        class: EzSystems\EzPlatformGraphQL\GraphQL\InputMapper\Search\Criteria\CriterionClass
        arguments:
            $criterionClass: 'eZ\Publish\API\Repository\Values\Content\Query\Criterion\Fulltext'
        tags:
            - {name: 'ezplatform_graphql.query_input_visitor', inputKey: 'Text'}

    EzSystems\EzPlatformGraphQL\GraphQL\InputMapper\Search\Criteria\ParentLocationId:
        class: EzSystems\EzPlatformGraphQL\GraphQL\InputMapper\Search\Criteria\CriterionClass
        arguments:
            $criterionClass: 'eZ\Publish\API\Repository\Values\Content\Query\Criterion\ParentLocationId'
        tags:
            - {name: 'ezplatform_graphql.query_input_visitor', inputKey: 'ParentLocationId'}


    EzSystems\EzPlatformGraphQL\GraphQL\InputMapper\Search\Criteria\Created:
        tags:
            - {name: 'ezplatform_graphql.query_input_visitor', inputKey: 'Created'}

    EzSystems\EzPlatformGraphQL\GraphQL\InputMapper\Search\Criteria\Modified:
        tags:
            - {name: 'ezplatform_graphql.query_input_visitor', inputKey: 'Modified'}

    EzSystems\EzPlatformGraphQL\GraphQL\InputMapper\Search\Criteria\Field:
        tags:
            - {name: 'ezplatform_graphql.query_input_visitor', inputKey: 'Field'}

    EzSystems\EzPlatformGraphQL\GraphQL\InputMapper\Search\SortClauseVisitor:
        tags:
            - {name: 'ezplatform_graphql.query_input_visitor', inputKey: 'SortBy'}
