services:
    EzSystems\EzPlatformGraphQL\Command\GeneratePlatformDomainTypesCommand:
        autoconfigure: true
        autowire: true
        tags:
            -  { name: console.command }

    EzSystems\EzPlatformGraphQL\Command\GeneratePlatformSchemaCommand:
        autoconfigure: true
        autowire: true
        tags:
            -  { name: console.command }

    bd_ezplatform_graphql.graph.mutation.section:
        class: EzSystems\EzPlatformGraphQL\GraphQL\Mutation\SectionMutation
        arguments:
            - "@ezpublish.api.service.section"
        tags:
            - { name: "overblog_graphql.mutation", alias: "CreateSection", method: "createSection" }
            - { name: "overblog_graphql.mutation", alias: "DeleteSection", method: "deleteSection" }

    EzSystems\EzPlatformGraphQL\GraphQL\InputMapper\SearchQueryMapper: ~

    EzSystems\EzPlatformGraphQL\DependencyInjection\Factory\SearchFeaturesFactory:
        arguments:
            $configurationProvider: '@ezpublish.api.repository_configuration_provider'
            $searchFeatures:
                solr: '@EzSystems\EzPlatformGraphQL\Search\SolrSearchFeatures'
                legacy: '@EzSystems\EzPlatformGraphQL\Search\LegacySearchFeatures'

    EzSystems\EzPlatformGraphQL\Search\SearchFeatures:
        factory: ['@EzSystems\EzPlatformGraphQL\DependencyInjection\Factory\SearchFeaturesFactory', build]

    EzSystems\EzPlatformGraphQL\Search\LegacySearchFeatures:
        arguments:
            $converterRegistry: '@ezpublish.persistence.legacy.field_value_converter.registry'

    EzSystems\EzPlatformGraphQL\Search\SolrSearchFeatures: ~

